### ISSUE TITLE
Weird UI behaviour and error.

### ISSUE THREAD

**Issue by FaizanKJSIT** [Falak-Chudasama/DevConnect#1]
When trying to create a project and adding more than 2 "required technologies", it overlaps with the the privacy status section and when posting the project it gives the following error: "Enter atleast one technology in the TECH-STACK".

## Issue:
[![Screenshot 2024-10-17 190315](https://github.com/user-attachments/assets/48e6bf7b-a55c-4d7e-adc3-5741f00a6232)](url)

![Screenshot 2024-10-17 190328](https://github.com/user-attachments/assets/96ad15ca-8b40-4c3e-a7a0-63463b59a4a8)

## Suggestion for the ui:
Something like this:

### Before entering first tech-stack: 
![Screenshot 2024-10-17 201124](https://github.com/user-attachments/assets/14d81604-ce35-439d-84f7-461325621eaa)

### After entering first tech-stack: 
![Screenshot 2024-10-17 202841](https://github.com/user-attachments/assets/d88414f1-bb95-4b7b-a833-a4b9f8786488)

**Comment by FaizanKJSIT** [comment]
While testing different things to see what went wrong, figured out this was because you are supposed to click on add then type and then press enter, clicking on add does not add the role. Even though it make sense it is very unintuitive, because usually clicking on add you assume the data is added and not a new field is added to add another value.

**Comment by Falak-Chudasama** [comment]
Sure that can be fixed by adding an event called "blur" tried that earlier
to make it as you said intuitive, but could not implement it pretty well,
will try that again and fix it
